Git.md, README.md
Add my git presentation from last fall.
=> Add Git presentation

InstallFest.md
This definitely needs improvement, but it's a start and should be good enough to provide to people who aren't able to attend the InstallFest but who need the image and instructions.
=> Add a brief, simple, imperfect InstallFest walkthrough

README.md
Add the InstallFest to a new section called "Special Events," for large
events that we hold less frequently.
Additionally, alphabetize the Full-Length Meetings Section.
Resolves #4
=> README.md: Add InstallFest and alphabetize

CommandLine.md
Fix formatting bugs and add missing Shakespeare command
=> Update command line demo notes

InternshipQA.md, README.md
Add internship panel questions for future use.
=> Internship Panel

Manpages.md, README.md
The powerpoint isn't actually done, but these are all the notes it will be based off of.
=> Add Manpage Presentation

LaTeX.md
I removed ShareLaTeX references.
=> Remove sharelatex references

LaTeX.md
Write "Get an" in front of Overleaf account. Add Overleaf tutorial link.
=> Add overleaf tutorial link

vm/welcome-to-vm.md
Cleanup the VM documentation a bit. Gloss over points that won't be
particularly relevant to students who are using the VM primarily for
class.
=> Update VM welcome documentation

Manpages.md, README.md, vim.md
Other Minor changes include fixing up some of the Manpages talk from last year and updating the readme.
=> Add Vim + Markdown talk

README.md, osquery.md
Add a lightning talk on osquery
=> add osquery lightning talk

IRC.md
Accidentally pushed the start directly to UUG's repo, woops.
Anyways, here's the finished version, hopefully through proper channels
=> Finish IRC Lightning talk notes

LaTeX.md
Might want to wait and see if we catch any typos during the presentation--feel free to add edits if that happens.
=> Improve LaTeX talk by adding more material

LaTeX.md
Fix typo found during presentation (as anticipated...) :P
=> Add missing algorithmic command

README.md, tmux.md
Finally getting this thing merged. Might need some grammar changes.
=> Add Tmux talk

CommandLine.md
Finally got around to making this PR again. I'm open to suggestions on this.
Resolves #40
=> rewrite command line presentation

LICENSE.md, README.md
You may be added to this PR as a reviewer because the repository contains content you authored. Acceptance of this PR indicates that your content will be offered under the CC-BY-SA 4.0 license.
Closes #37
=> Add CC-BY-SA 4.0 license document

vm/README.md, vm/common-troubleshooting.md
Since there will be yet another issue to troubleshoot this year with Hyper-V, it will be good to have all the common troubleshooting stuff in one place.
The last option can also be resolved by upgrading to Windows 10 Pro and actually using Hyper-V; however, apparently VirtualBox's support for Hyper-V isn't great and results in awful performance (highlighted by a turtle icon in the bottom right corner of the window).
=> Add documentation for common troubleshooting

Vim.md
Just a few quick updates for this year. Mostly spelling fixes, but at least two new sections and one link fix.
=> Update Vim talk

Vim.md
=> Fix a few Vim typos

README.md, Systemd.md
=> Add systemd documentation

README.md, Scripting.md
Just setting this here for people to look over while I talk. expect horrible spelling mistakes. Will go through later/tomorrow if no one else wants to try to fix it first.
=> Add Scripting talk

Git.md
I found this while working through the Git tutorial and verified it with Dr.Lam.
=> Fix typo in GitHub tutorial

README.md, containers/building.md
Still working on this, but hoping to merge before presenting tomorrow so people can follow along.
=> Add container building talk

LaTeX.md
New content:
- Tilde spacing for `\ref` and `\cite` (as is custom)
- Zotero link for bibliography management
- TikZ content (thanks @Advill!)
=> Improve LaTeX tutorial

AdventuresInProc.md, CommandLine.md, IRC.md, InstallFest.md, InternshipQA.md, LICENSE.md, LaTeX.md, Manpages.md, NextCloudAWS.md, README.md, Scripting.md, Systemd.md, Vim.md, osquery.md, tmux.md, window-and-desktop-environments.md
This should satisfy lint complaints on remaining top-level files.
=> Fix remaining top-level lint

GPL.md, README.md
Catching up on stale branches here
=> Add GPL lightning talk

tmux.md
This commit fixes a few typos and spelling errors, and adds a missing
quick ref item.
=> Clean up Tmux tutorial

.github/workflows/pdf-build.yml
=> Switch PDF build to pandoc

README.md, groff/index.md
=> Add groff presentation - take 2

homelab.md
=> Add homelabbing presentation

systemd-slides.md
I'll get this right eventually
=> Fix systemd ssh typo

.markdownlint.json, cicd.patch, cicd/index.md
=> surely, this will fix the slides

containers/kubernetes.md
I still need to publish the setup scripts, but getting the slides together for now.
=> Update Kubernetes slides for 2025
